server:
  port: 9300

spring:
  profiles:
    active: dev

dynamic:
  config:
    password: '100030'
    phoneNumber: '15365010926'
    venuePriority: '16,20,11,15,6,17,18,19,1,2,12,13,14,7,8'

security:
  basic:
    enabled: false
