server:
  port: 29300

spring:
  profiles:
    active: dev

schedule:
    autoPanicOrder:
      cron: '0,1,2,4,6,8,10,12,14,16,26,36,46,56 0,1,2,3,4,5 6 * * ?'

dynamic:
  config:
    password: '100030'
    phoneNumber: '15365010926'
    venuePriority: '16,20,17,18,19,11,15,6,1,2,12,13,14,7,8'

security:
  basic:
    enabled: false
